### PR TITLE
Added test support for V3 excel template

### PR DESCRIPTION
**Pull request by Graeme-Smith**
BASHer now supports the version 3 Excel Template which is required for consang AR cases and XL cases.  This required several small cahnges to how the test suite parses the excel filenames and automatically generates the tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @rebeccahaines1)

___
*[`snp_haplotyper/excel_parser.py` line 216 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16thKGCFA-LBRl7vSu:-O16thKGCFA-LBRl7vSv:b-88hbvo) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L216)):*
> ```Python
>             cell_location = dn.attr_text.split(":")[0].split("!")[1].replace("$", "")
>             cell_value = str(data_entry_sheet[cell_location].value).strip()
>             # print(cell_location, cell_value)
> ```

can you remove this comment?
___
*[`snp_haplotyper/excel_parser.py` line 360 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16tnxPAdSXcSpu1Dtn:-O16tnxPAdSXcSpu1Dto:b-k8anzs) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L360)):*
> ```Python
>         .replace("excel_test_X_linked_", "")
>         .replace("_v2", "")
>         .replace("_v3", "")
> ```

What are these doing?

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

**Comment by Graeme-Smith** [comment]
*[`snp_haplotyper/excel_parser.py` line 360 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16tnxPAdSXcSpu1Dtn:-O3JZUmS1Can2VgX0mjD:b-kibvsa) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L360)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

What are these doing?
</blockquote></details>

The produces each test based on the name of the excel spreadsheet, and the tests name will be based on that spreadsheet name.  However when we want to look up the expected test results we just want to look up the appropriate data in the benchmark JSON.  For example, if we have three excels:
sample1.xlxs
sample_v2.xlxs
sample_v3.xlxs
We want three tests named:
sample1
sample_v2
sample_v3
But when looking up the benchmark result in the JSON you want those for 'sample1' - no matter the template used they are all expected to return the same results, that is essentially the purpose of the test.

**Comment by Graeme-Smith** [comment]
*[`snp_haplotyper/excel_parser.py` line 216 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16thKGCFA-LBRl7vSu:-O3JYl-H5_2NnEB2AWWm:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L216)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

can you remove this comment?
</blockquote></details>

Done.

**Comment by rebeccahaines1** [comment]
*[`snp_haplotyper/excel_parser.py` line 216 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16thKGCFA-LBRl7vSu:-O3NwN4q26w9I6WpAVwK:b-s4xaqi) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L216)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

comment is still there. please can you resolve in the next update?

**Review by rebeccahaines1 — APPROVED** [review]
> Dismissed @RachelDuffin from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10)* status: all files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

**Comment by rebeccahaines1** [comment]
*[`snp_haplotyper/excel_parser.py` line 360 at r1](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10#-O16tnxPAdSXcSpu1Dtn:-O3NwcLtClCxcZxm-E06:bd37ya1) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/b0efd0cee4ba7bc7d3b7ae64bd0d45016f0dc37f/snp_haplotyper/excel_parser.py#L360)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

The produces each test based on the name of the excel spreadsheet, and the tests name will be based on that spreadsheet name.  However when we want to look up the expected test results we just want to look up the appropriate data in the benchmark JSON.  For example, if we have three excels:
sample1.xlxs
sample_v2.xlxs
sample_v3.xlxs
We want three tests named:
sample1
sample_v2
sample_v3
But when looking up the benchmark result in the JSON you want those for 'sample1' - no matter the template used they are all expected to return the same results, that is essentially the purpose of the test.
</blockquote></details>

thanks for clarifying

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/10)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
